"""ajout de nouveaux champs dans le model user

Revision ID: 98305e3e3e91
Revises: e8de56ab27dd
Create Date: 2025-07-01 21:06:53.972118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98305e3e3e91'
down_revision = 'e8de56ab27dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
